### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by viktoryia40** [viktoryia40/ProgFullStack#2]
**Agregar contenido al documento IEEE 830**

Tarea 1  _Introducción_
Tarea 2  _Propósito_ **Clarisa**
Tarea 3 _Alcance_ **Fabio**
Tarea 4  _Resumen_ **Morena**
Tarea 5  _Descripción general_
Tarea 6  _Perspectiva del producto_ **Martin**
Tarea 7  _Restricciones_
Tarea 8  _Requisitos específicos_
Tarea 9  _Product Backlog_ **Celeste**
Tarea 10 _Sprints_

**Comment by FabioLunaa** [comment]
Luna Fabio trabajo con el punto ALCANCE del documento IEEE 830.
